FROM rabbitmq:3.11-management

# Chuyển sang user root để cài đặt
USER root

# Cập nhật và cài đặt wget, sau đó dọn dẹp cache
RUN apt-get update && apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/*

# Download plugin delayed message trực tiếp
RUN wget -O /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.11.1.ez \
    https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.11.1/rabbitmq_delayed_message_exchange-3.11.1.ez

# Kích hoạt plugin offline
RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange

# Chuyển về user rabbitmq
USER rabbitmq

# Expose ports
EXPOSE 5672 15672